#!/usr/bin/env python

import sys

# from rqt_destitution_clicker.PluginModule import MapGraph
from rqt_gui.main import Main

# plugin = 'rqt_destitution_clicker'
# main = Main(filename=plugin)
# sys.exit(main.main(standalone=plugin))
main = Main()
sys.exit(main.main(sys.argv, standalone='rqt_destination_clicker.map_graph.MapGraph'))
